In [2]:
from pandas import Series
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import cross_validation, linear_model 
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.metrics import confusion_matrix
%matplotlib inline

C:\Users\Becca's PC\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Read in csv file

In [3]:
data = pd.read_csv("NFLPlaybyPlay2015.csv", dtype={'DefTwoPoint': str}, na_values=['NA'])
data.head()
df = data

Drop rows without relevent data (i.e. posteam, defensive team, etc)

## Data Models

#### Play prediction (using 4 Dallas cowboy games

In [4]:
ptdf = pd.read_csv("PlayType.csv")

X = ptdf[ptdf.columns.difference(["PlayType"])]
y = ptdf["PlayType"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state=42)

gnb = GaussianNB()

ptdf[:5]
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print (gnb.score(X_test, y_test))

[[ 8  0  0  0  0  0  0  0  1  0]
 [ 0  6  5 17  0  0  0  0  7  1]
 [ 0  1 13 28  0  0  0  0 10  0]
 [ 0  0  3  6  0  0  0  0  2  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  1  0  0  2  0  0  0  0]
 [ 0  0  1  0  0  0  8  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  3  0  0  0  0  1  0]
 [ 0  0  0  1  0  0  0  0  0  1]]
0.375939849624


#### Challenges

In [5]:
chdata = pd.read_csv("challenges.csv")

chdata[:5]


X = chdata[chdata.columns.difference(["ChalOverturned"])]
y = chdata["ChalOverturned"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state=42)

gnb = GaussianNB()

gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print (gnb.score(X_test, y_test))

[[11 61]
 [ 9 55]]
0.485294117647


#### Gradient Boosting

In [10]:
from sklearn.ensemble import GradientBoostingClassifier

X = chdata[chdata.columns.difference(["ChalOverturned"])]
y = chdata["ChalOverturned"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state=0)
clf = GradientBoostingClassifier(n_estimators=20, learning_rate=.2, max_depth=2, random_state=0).fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred, labels=[0,1]))
print(clf.score(X_test, y_test))


[[74  3]
 [28 31]]
0.772058823529
